name: 'BasherItems'
version: '1.3.0'
main: ru.basher.items.ItemsPlugin
api-version: 1.16
authors: [ Aleks_Basher ]
website: 'https://t.me/aleks_basher'
depend: [ PlayerPoints ]
commands:
  basheritems:
  trap-skins:
