name: BasherEconomy
version: '1.1.2'
main: ru.basher.economy.EconomyPlugin
api-version: 1.16
authors: [ Aleks_Basher ]
website: 'https://t.me/aleks_basher'
softdepend:
  - CMI
  - Essentials
depend: [ Vault ]
commands:
  bashereconomy:
  balance:
  balancetop:
  eco:
  pay:
  paytoggle:
  payconfirmtoggle: