products:
  product1:
    item: # Здесь параметр slot не учитывается
      name: '&6Какао-бобы'
      material: COCOA_BEANS
    oldPrice: 3.0 # Визуально старая цена за 1 штуку
    price: 3.0 # Цена за 1 штуку
    maxSales: 128 # Максимальное количество скупок для этого предмета
    freezeCooldown: 3600 # Время регенерации в секундах после достижения maxBuys