name: BasherDuels
version: '1.2.6'
main: ru.basher.duels.DuelsPlugin
api-version: 1.16
authors: [ Aleks_Basher ]
website: 'https://t.me/aleks_basher'
load: POSTWORLD
depend: [ PlaceholderAPI ]
softdepend: [ MultiWorld ]
commands:
  basherduels:
  duel: